version: "1"

services:
  nextjs:
    container_name: "nextjs"
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    restart: always
    ports:
      - 3000:3000

# networks:
#   - app_network

